name: 'Check PR commits signed off'
description: 'Checks for a sign-off in every commit in a pull request'
author: 'GitHub'
inputs:
  token:
    description: 'GitHub token for commenting on PRs, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  commits_url:
    description: 'GitHub PR commit url'
    default: ${{ github.event.pull_request.commits_url }}
  issue_url:
    description: 'GitHub PR issue url'
    default: ${{ github.event.pull_request.issue_url }}


runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: check-circle
  color: purple
