name: Check signed commits in PR
on: pull_request_target
jobs:
  check-signed-off:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: A test
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check signed commits
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
