name: Find signed commits

on:
  pull_request_target:

jobs:
  check-sign-off:
    name: Write comment if unsigned commits found
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-latest

    steps:
      - uses: cloudforet-io/review-pr-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
